### ISSUE TITLE
https://hackout3.github.io/ does not update

### ISSUE THREAD

**Issue by thibautjombart** [Hackout3/hackout3.github.io#1]
Changes on https://github.com/Hackout3/hackout3.github.io (hg-pages branch) no longer seem to affect the content of the website.
Related:
http://stackoverflow.com/questions/20422279/github-pages-are-not-updating
and
http://stackoverflow.com/questions/24713112/my-github-page-wont-update-its-content

But no working solution for our case. 
@karthik @richfitz  any idea?

**Comment by thibautjombart** [comment]
Fixed - needed to have a branch 'master' instead of gh-pages.

**Comment by richfitz** [comment]
nice one.

**Comment by thibautjombart** [comment]
=D
